name: gltut-framework

dependencies:
    - Boolean
    - GPipe
    - GPipe-GLFW
    - base
    - linear

ghc-options:
    - -Wall
    - -threaded -rtsopts -with-rtsopts=-N

library:
    source-dirs: lib

tests:
    doctest:
        main: Doctest.hs
        dependencies:
            - doctest
            - QuickCheck
