name: gltut-framework

dependencies:
    - Boolean
    - GPipe
    - GPipe-GLFW
    - base
    - linear
    - stm

ghc-options:
    - -Wall

library:
    source-dirs: lib
executables:
    example:
        main: Example.hs
        ghc-options:
            - -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - gltut-framework
tests:
    doctest:
        main: Doctest.hs
        dependencies:
            - doctest
            - QuickCheck
