name: gltut-framework

dependencies:
    - Boolean
    - GPipe
    - GPipe-GLFW
    - base
    - linear
    - stm

ghc-options:
    - -Wall

library:
    source-dirs: lib

tests:
    doctest:
        main: Doctest.hs
        dependencies:
            - doctest
            - QuickCheck
