name: gltut-tut01

dependencies:
    - GPipe
    - GPipe-GLFW
    - base
    - gltut-framework

ghc-options:
    - -Wall
    - -threaded -rtsopts -with-rtsopts=-N

executables:
    # Tutorials
    tut1:
        main: tut1.hs
