name: tut02

dependencies:
    - GPipe
    - GPipe-GLFW
    - base

ghc-options:
    - -Wall
    - -threaded -rtsopts -with-rtsopts=-N

executables:
    # Tutorials
    FragPosition:
        main: FragPosition.hs
    VertexColors:
        main: VertexColors.hs
    # Further study
    ## For the "settable viewport" further study, you can just move the window
    ## around your screen or resize it.
    FragPosition_VertexColors:
        main: FragPosition_VertexColors.hs
